import { describe, it, expect } from 'vitest';
import { optimizeSvg, formatBytes } from './svgOptimize';

const MESSY = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by an editor -->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
     width="100" height="100" viewBox="0 0 100 100">
  <metadata>some editor junk</metadata>
  <title>My icon</title>
  <g inkscape:label="Layer 1" id="layer1">
    <path d="M 10.123456 20.987654 L 30.111111 40.999999 Z" fill="#ff0000"/>
  </g>
</svg>`;

describe('optimizeSvg', () => {
  it('shrinks the file and reports the saving', () => {
    const r = optimizeSvg(MESSY);
    expect(r.optimizedBytes).toBeLessThan(r.originalBytes);
    expect(r.savedPercent).toBeGreaterThan(0);
    expect(r.savedPercent).toBeLessThanOrEqual(100);
  });

  it('strips prolog, comments, metadata and editor namespaces', () => {
    const { svg } = optimizeSvg(MESSY);
    expect(svg).not.toContain('<?xml');
    expect(svg).not.toContain('<!--');
    expect(svg).not.toContain('<metadata>');
    expect(svg).not.toContain('inkscape:');
    expect(svg).not.toContain('xmlns:inkscape');
  });

  it('keeps everything needed to render', () => {
    const { svg } = optimizeSvg(MESSY);
    expect(svg).toContain('xmlns="http://www.w3.org/2000/svg"');
    expect(svg).toContain('viewBox="0 0 100 100"');
    expect(svg).toContain('fill="#ff0000"');
    expect(svg).toContain('<path');
    // id is referenced by nothing here, but stripping ids breaks real files
    expect(svg).toContain('id="layer1"');
  });

  it('keeps title/desc unless asked to remove them', () => {
    expect(optimizeSvg(MESSY).svg).toContain('<title>');
    expect(optimizeSvg(MESSY, { removeTitleDesc: true }).svg).not.toContain('<title>');
  });

  it('rounds numbers to the requested precision', () => {
    const { svg } = optimizeSvg(MESSY, { precision: 1 });
    expect(svg).toContain('M 10.1 21 L 30.1 41 Z');
  });

  it('drops the leading zero on sub-unit numbers', () => {
    const { svg } = optimizeSvg('<svg xmlns="http://www.w3.org/2000/svg"><path d="M 0.5 -0.25 Z"/></svg>', { precision: 2 });
    expect(svg).toContain('M .5 -.25 Z');
  });

  it('removes width/height only when a viewBox exists', () => {
    const withBox = optimizeSvg(MESSY, { removeDimensions: true }).svg;
    expect(withBox).not.toMatch(/<svg[^>]*\swidth=/);
    expect(withBox).toContain('viewBox');

    const noBox = '<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><path d="M0 0Z"/></svg>';
    // Without a viewBox, dropping the dimensions would collapse the graphic.
    expect(optimizeSvg(noBox, { removeDimensions: true }).svg).toMatch(/width="10"/);
  });

  it('strips scripts and inline event handlers', () => {
    const nasty = `<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script><rect onclick="steal()" width="1" height="1"/></svg>`;
    const { svg } = optimizeSvg(nasty);
    expect(svg).not.toContain('<script');
    expect(svg).not.toContain('onclick');
    expect(svg).toContain('<rect');
  });

  it('strips javascript: and data:text/html hrefs but keeps normal ones', () => {
    const nasty = `<svg xmlns="http://www.w3.org/2000/svg"><a xlink:href="javascript:alert(1)"><rect width="1" height="1"/></a><a href="https://example.com"><circle r="1"/></a><use href="#shape"/></svg>`;
    const { svg } = optimizeSvg(nasty);
    expect(svg).not.toContain('javascript:');
    expect(svg).toContain('href="https://example.com"');
    // Internal references must survive — they are how <use> and gradients work.
    expect(svg).toContain('href="#shape"');
  });

  it('preserves gradient definitions and their references', () => {
    const grad = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><defs><linearGradient id="g"><stop offset="0" stop-color="#fff"/></linearGradient></defs><rect fill="url(#g)" width="10" height="10"/></svg>`;
    const { svg } = optimizeSvg(grad);
    expect(svg).toContain('linearGradient');
    expect(svg).toContain('id="g"');
    expect(svg).toContain('url(#g)');
  });

  it('is idempotent — optimizing twice changes nothing further', () => {
    const once = optimizeSvg(MESSY).svg;
    expect(optimizeSvg(once).svg).toBe(once);
  });

  it('lists what it removed', () => {
    const { notes } = optimizeSvg(MESSY);
    expect(notes).toContain('Comments');
    expect(notes).toContain('Editor metadata');
    expect(notes.length).toBeGreaterThan(2);
  });

  it('handles an already-minimal file without reporting a negative saving', () => {
    const tiny = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1"><path d="M0 0Z"/></svg>';
    const r = optimizeSvg(tiny);
    expect(r.savedPercent).toBeGreaterThanOrEqual(0);
  });
});

describe('formatBytes', () => {
  it('scales the unit to the size', () => {
    expect(formatBytes(512)).toBe('512 B');
    expect(formatBytes(2048)).toBe('2.0 KB');
    expect(formatBytes(5 * 1024 * 1024)).toBe('5.00 MB');
  });
});
